### PR TITLE
Updated unit-testing.md

### PR DESCRIPTION
**Pull request by GarethOates**
There was no mention of having to add the Microsoft.EntityFrameworkCore package to the Unit Test project.

### CODE REVIEW

**Comment by nbarbettini** [comment]
Shouldn't that be pulled in transitively because of the reference to the main project?

**Comment by GarethOates** [comment]
That wasn’t my experience. Let me double check again to make sure but I remember not being able to build it until I included that package explicitly.

**Comment by nbarbettini** [comment]
That's weird. I'm traveling at the moment, thanks for looking into it!

**Comment by GarethOates** [comment]
You were right. I removed the explicit reference to the Microsoft.EntityFrameworkCore package in the UnitTest project and it still built.  It must have just been a bug in VS Code or something.

Thanks for a great resource! :)

**Comment by nbarbettini** [comment]
No worries. Yeah, VS Code can be a little sketchy with that sometimes (the restore task doesn't always run automatically).

Thanks for the feedback! Feel free to send any more issues or PRs. 😄

**Pull request closed without merging**
