### PR TITLE
Update create-models.md

### PR DESCRIPTION
**Pull request by aannenko**
Inaccurate transcription of the acronym POCO.
POCO = Plain Old CLR Object.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1#overview

### CODE REVIEW

**Comment by nbarbettini** [comment]
Thanks for your contribution!

I went back and forth on this myself. Many readers of this book will not know what "CLR" means, but they do know they are learning C#. Do you think we should also explain what CLR is?

**Comment by aannenko** [comment]
> Do you think we should also explain what CLR is?

A very short description would be enough I guess, otherwise the readers may be confused with the term in the future when they start reading other C#/VB books and articles.

First sentence from the Wiki sounds pretty clear:
"The Common Language Runtime (CLR), the virtual machine component of Microsoft's .NET framework, manages the execution of .NET programs."

Though it can be rephrased a bit to fit the context better:
"Common Language Runtime (CLR) is a special component of the .NET framework, it manages the execution of C# programs. In other words, CLR is what really runs your application. All C# code gets translated into CLR code when you build your app."

**Comment by mattwelke** [comment]
@aannenko I would be careful with terminology in the rephrasing. There's a world of difference between **.NET framework** and **.NET Framework**.

**Comment by aannenko** [comment]
Feel free to

**Comment by aannenko** [comment]
@nbarbettini this is your book so feel free to do whatever you decide to do about this PR, it can be treated as a non-insistent suggestion.

**Pull request closed without merging**
